export * from './checkValid'
export * from './emitter'
export * from './getChangedNames'
export * from './getFieldMetadata'
export * from './getInitialState'
export * from './handleFieldMemo'
export * from './isTouched'
export * from './touchAll'
export * from './uuid'

export const isDOM = typeof window !== 'undefined'
